owner: koj-co
repo: status
user-agent: KojBot
sites:
  - name: Koj.co
    url: https://koj.co/en-ch/
  - name: Koj API
    url: https://api.koj.co
  - name: Go.Koj
    url: https://go.koj.co/url-shortener-uptime-monitoring-24hu9q0ir1290
  - name: Koj CDN
    url: https://kojcdn.com
assignees:
  - AnandChowdhary
status-website:
  cname: status.koj.co
  logoUrl: https://avatars3.githubusercontent.com/u/65495851?s=88&v=4
  faviconSvg: https://koj.co/favicon.svg
  favicon: https://koj.co/favicon-32x32.png
  name: Koj Status
  logoHref: https://koj.co
